// user action types
export const SET_CURRENT_USER = 'SET_CURRENT_USER'


// cart action types
export const TOOGLE_CART_HIDDEN = 'TOOGLE_CART_HIDDEN'
export const ADD_ITEM = 'ADD_ITEM'
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART'
export const REMOVE_ITEM = 'REMOVE_ITEM'

// shop action types
export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS'
export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START'
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS'
export const FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTIONS_FAILURE'
